version: '3'

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8282:80"
    volumes:
      - ./dockerfiles/nginx:/etc/nginx/conf.d/
      - ./html:/var/www/html
    networks:
      - mynet


  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./html:/var/www/html
    networks:
      - mynet

networks:
  mynet:
